name: PHP Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
    - uses: actions/checkout@v2

    - name: OS info
      run: cat /etc/os-release

    - name: "Install PHP"
      uses: shivammathur/setup-php@v2
      with:
        coverage: "none"
        php-version: "${{ matrix.php-version }}"
        extensions: intl

    - name: PHP info
      run: |
        php -v
        php -m

    - name: Validate composer.json and composer.lock
      run: composer --working-dir=site validate

    - name: Run tests
      run: composer --working-dir=site test

    - name: Failed test output, if any
      if: failure()
      run: for i in $(find ./site/tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

    - name: Upload test code coverage
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Test code coverage (PHP ${{ matrix.php-version }})
        path: 'site/temp/coverage.html'
        retention-days: 5
