name: PHP Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add missing PHP extensions
      run: composer --working-dir=site add-missing-extensions-prod

    - name: OS info
      run: cat /etc/os-release

    - name: PHP info
      run: |
        php -v
        php -m

    - name: Validate composer.json and composer.lock
      run: composer --working-dir=site validate

    - name: Run tests
      run: composer --working-dir=site test-prod

    - name: Failed test output, if any
      if: failure()
      run: for i in $(find ./site/tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
