name: PHP tests

on: [push]

jobs:
  info:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - name: OS info
      run: cat /etc/os-release
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - name: PHP info
      run: |
        php -v
        php -m

  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer.json and composer.lock
      run: composer --working-dir=site validate

  check-file-patterns:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site check-file-patterns


  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site lint

  lint-latte:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site lint-latte

  lint-neon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site lint-neon

  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - name: Get PHP_CodeSniffer cache file pattern
      id: phpcs-cache
      run: echo "::set-output name=file::$(php -r "echo sys_get_temp_dir() . '/phpcs.*';")"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.phpcs-cache.outputs.file }}
        key: phpcs-cache-php${{ matrix.php-version }}
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site phpcs

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - name: Get PHPStan result cache directory
      id: phpstan-cache
      run: echo "::set-output name=dir::$(php -r "echo sys_get_temp_dir() . '/phpstan';")"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.phpstan-cache.outputs.dir }}
        key: phpstan-cache-php${{ matrix.php-version }}
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site phpstan

  phpstan-vendor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - name: Get PHPStan result cache directory
      id: phpstan-cache
      run: echo "::set-output name=dir::$(php -r "echo sys_get_temp_dir() . '/phpstan';")"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.phpstan-cache.outputs.dir }}
        key: phpstan-vendor-cache-php${{ matrix.php-version }}
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site run-script --timeout=600 phpstan-vendor

  tester:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
    - uses: actions/checkout@v3
    - run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
    - run: composer --working-dir=site tester
    - name: Failed test output, if any
      if: failure()
      run: for i in $(find ./site/tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - name: Upload test code coverage
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: Test code coverage (PHP ${{ matrix.php-version }})
        path: 'site/temp/coverage.html'
        retention-days: 5
